spring:
  application:
    name: giju

  profiles:
    active: local
    group:
      "prod": "prod, secret, swagger"
      "local": "local, secret, swagger"

logging:
  level:
    org.springframework.security: DEBUG

order:
  targetPrice: 30000
  delivery-charge: 3000



jwt:
  expirationtime:
    accessTime: 21600000
    refreshTime: 21600000
  secret: ${JWT_SECRET:defaultfordevalsjfielsjfinaajfowinblxiejfwoihbya}