
spring:

  datasource:
    url: ${DB_URL:dummy}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:  ${DB_USERNAME:dummy}
    password:  ${DB_PASSWORD:dummy}
  jpa:
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show-sql: true

app:
  base-url: ${DNS_URL:dummy}
front:
  uri: ${FRONT_URI:https://giju.vercel.app}