spring:
  application:
    name: giju

  profiles:
    active: local
    group:
      "prod": "prod, secret"
      "local": "local, secret"

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  expirationtime:
    refresh: 216000
    access: 216000