version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "giju-task"
        LoadBalancerInfo:
          TargetGroupInfoList:
            - Name: "ecs-blue-tg"
            - Name: "ecs-green-tg"
        PlatformVersion: "LATEST"
