version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "giju-task:9"
        LoadBalancerInfo:
          ContainerName: "giju-container"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
